### PR TITLE
Adds `ctrlc` and SIGINT handling

### LINKED ISSUE #12: save the state on SIGINT
Catch `SIGINT` somehow and save the state of the app the same way we do it after the event loop: https://github.com/tsoding/todo-rs/blob/2b71072386ad200cd5592fc6138c6856fe283386/src/main.rs#L370

Don't overcompilcate.

### PR DESCRIPTION
**Pull request by koutoftimer**
Closes #12

### CODE REVIEW

**Review by rexim — CHANGES_REQUESTED** [review]
I'm not sure what exactly was broken in a8439d00e38fe731b2be647aada6323a738b91a3 and what exactly was the fixed. Could you please elaborate?

**Comment by koutoftimer** [comment]
@rexim `getch` is not in blocking mode any more. This mean that any notification message will be cleared after first ui render, technically after 100ms. Fix is not to clear notification on render, but on real user input.

**Comment by koutoftimer** [comment]
@rexim is it clear enough?

**Comment by rexim** [comment]
@koutoftimer oh, I see! Makes sense! Thank you for your contribution!

**Pull request closed without merging**
